name: A workflow for my hello World file
branding:
  icon: "bell"  
  color: "red"
on: [push, pull_request] 
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Irvv17"
    branding:
      icon: "bell"  
      color: "red"